repos:
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: python test.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
