trainer:
  max_epochs: -1
  accelerator: gpu
  enable_checkpointing: True
  overfit_batches: 0.0
  accumulate_grad_batches: 16
  gradient_clip_val: 1.0
  resume_from_checkpoint: null
  log_every_n_steps: 2

model:
  lr: 7.5e-5
  d_model: 512
  n_heads: 8
  n_layers: 4
  mask_prob: 0.20
  label_smoothing: 0.1
  dropout: 0.1
  warmup_steps: 100

data:
  dataset_config: configs/dataset/mnli.yaml
  batch_size: 16
  validation_size: 0.2
  num_workers: 20
