trainer:
  max_epochs: -1
  accelerator: gpu
  enable_checkpointing: True
  overfit_batches: 0.0
  accumulate_grad_batches: 1
  gradient_clip_val: 2.0
  resume_from_checkpoint: null

model:
  lr: 3.0e-5
  d_model: 128
  n_heads: 8
  n_layers: 2
  mask_prob: 0.15
  label_smoothing: 0.1
  dropout: 0.1
  warmup_steps: 10000

data:
  dataset_config: configs/dataset/mnli.yaml
  batch_size: 32
  validation_size: 0.2
  num_workers: 20
