trainer:
  max_epochs: -1
  accelerator: gpu
  enable_checkpointing: False
  overfit_batches: 0.000003125
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  resume_from_checkpoint: null
  log_every_n_steps: 1

model:
  lr: 1e-4
  d_model: 768
  n_heads: 12
  n_layers: 12
  mask_prob: 0.20
  label_smoothing: 0.0
  dropout: 0.0
  warmup_steps: 1

data:
  dataset_config: configs/dataset/mnli.yaml
  batch_size: 1
  validation_size: 0.0
  num_workers: 20
