trainer:
  max_epochs: -1
  accelerator: gpu
  enable_checkpointing: True
  overfit_batches: 0.0
  accumulate_grad_batches: 16
  gradient_clip_val: 2.0
  resume_from_checkpoint: null

model:
  lr: 3.0e-4
  d_model: 768
  n_heads: 12
  n_layers: 12
  label_smoothing: 0.1
  dropout: 0.1
  warmup_steps: 200

data:
  dataset_config: configs/dataset/mnli.yaml
  batch_size: 8
  validation_size: 0.2
  num_workers: 20
